// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }



// import "./globals.css";
// import Navbar from "@/components/layout/Navbar";
// // import FooterPart from "@/components/layout/Footer";
// import Footer from "@/components/layout/footer/Footer";

// export const metadata = {
//   title: "Atrium Estates",
//   description: "Trusted Real Estate Solutions",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navbar />
//         {/* <FooterPart /> */}
//         <Footer />

//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/footer/Footer";

import ScrollToTop from "@/components/common/ScrollToTop";

export const metadata = {
  title: "100acress.com",
  description: "Trusted Real Estate Solutions",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
        <Navbar />

        <ScrollToTop />

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}