export const footerData = {
  brand: {
    name: "100acress",
    tagline:
      "India's leading luxury real estate platform. Buy, sell & invest in premium properties across India & Dubai.",
    phone: "+91 8500 900 100",
    email: "support@100acress.com",
    locations: ["Gurugram, Haryana", "Dubai, UAE"],
  },
  stats: [
    { value: "50,000+", label: "Properties Listed" },
    { value: "25,000+", label: "Happy Customers" },
    { value: "RERA", label: "Compliant Projects" },
    { value: "Since 2019", label: "Trusted Platform" },
  ],
  quickLinks: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about-us" },
    { label: "Luxury Projects", href: "/luxury-projects" },
    { label: "Branded Residences", href: "/branded-residences" },
    { label: "Blog", href: "/blog" },
    { label: "Resale Properties", href: "/resale-properties" },
    { label: "Rental Properties", href: "/rental-properties" },
    { label: "Career with Us", href: "/careers" },
    { label: "Testimonials", href: "/testimonials" },
    { label: "Contact", href: "/contact" },
  ],
  popularCities: [
    { label: "Flats in Gurugram", href: "/flats-in-gurugram" },
    { label: "Flats in Noida", href: "/flats-in-noida" },
    { label: "Flats in Ayodhya", href: "/flats-in-ayodhya" },
    { label: "Flats in Panipat", href: "/flats-in-panipat" },
    { label: "Flats in Kasauli", href: "/flats-in-kasauli" },
    { label: "Flats in Karnal", href: "/flats-in-karnal" },
    { label: "Flats in Pushkar", href: "/flats-in-pushkar" },
    { label: "Flats in Delhi", href: "/flats-in-delhi" },
    { label: "Flats in Goa", href: "/flats-in-goa" },
    { label: "Flats in Mumbai", href: "/flats-in-mumbai" },
    { label: "Flats in Panchkula", href: "/flats-in-panchkula" },
    { label: "Flats in Sonipat", href: "/flats-in-sonipat" },
    { label: "Flats in Jalandhar", href: "/flats-in-jalandhar" },
    { label: "Flats in Alwar", href: "/flats-in-alwar" },
  ],
  topDevelopers: [
    { label: "Godrej Properties", href: "/developer/godrej-properties" },
    { label: "DLF Homes", href: "/developer/dlf-homes" },
    { label: "Emaar India", href: "/developer/emaar-india" },
    { label: "Birla Estates", href: "/developer/birla-estates" },
    { label: "Adani Realty", href: "/developer/adani-realty" },
    { label: "Experion Developers", href: "/developer/experion-developers" },
    { label: "Signature Global", href: "/developer/signature-global" },
    { label: "Sobha Developers", href: "/developer/sobha-developers" },
    { label: "Central Park", href: "/developer/central-park" },
    { label: "Trump Towers", href: "/developer/trump-towers" },
    { label: "ELAN Group", href: "/developer/elan-group" },
    { label: "Max Estates", href: "/developer/max-estates" },
    { label: "M3M India", href: "/developer/m3m-india" },
    { label: "SmartWorld Developers", href: "/developer/smartworld-developers" },
    { label: "BPTP Limited", href: "/developer/bptp-limited" },
  ],
  primeLocations: [
    { label: "Projects on Sohna Road", href: "/projects-sohna-road" },
    { label: "Projects on Golf Course Road", href: "/projects-golf-course-road" },
    { label: "Projects on Dwarka Expressway", href: "/projects-dwarka-expressway" },
    { label: "Projects on New Gurgaon", href: "/projects-new-gurgaon" },
    { label: "Projects on Southern Peripheral Road", href: "/projects-spr" },
    { label: "Projects on Golf Course Extension Road", href: "/projects-gcr-extension" },
  ],
  toolsAndServices: [
    { label: "EMI Calculator", href: "/emi-calculator" },
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms & Conditions", href: "/terms-and-conditions" },
    { label: "Disclaimer", href: "/disclaimer" },
  ],
  gurgaonPills: [
    "Fully Furnished Flats in Gurgaon",
    "Penthouses in Gurgaon",
    "Semi Furnished Flats in Gurgaon",
    "Independent Floor for Sale in Gurgaon",
    "Independent Houses For Sale in Gurgaon",
    "Flats For Sale under 1 Cr in Gurgaon",
    "Flats For Sale under 5 Cr in Gurgaon",
    "Flats For Sale under 10 Cr in Gurgaon",
    "Flats For Sale under 20 Cr In Gurgaon",
    "Affordable Homes in Gurgaon",
    "Farmhouses in Gurgaon",
    "Studio Apartments in Gurgaon",
    "Resale Property in Gurgaon",
    "Rental Property in Gurgaon",
    "Senior Living in Gurgaon",
    "Affordable Plots in Gurgaon",
    "Residential Flats in Gurgaon",
    "Retail Shops in Gurgaon",
    "Builder Floor in Gurgaon",
    "SCO Plots in Gurgaon",
    "Luxury Villas in Gurgaon",
    "Industrial Plots in Gurgaon",
    "Farmhouse in Gurgaon",
    "Shop Cum Office Plots in Gurgaon",
    "Plots in Gurgaon",
    "Deen Dayal (DDJAY) Plots in Gurgaon",
  ],
  legal: [
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms & Conditions", href: "/terms-and-conditions" },
    { label: "Sitemap", href: "/sitemap.xml" },
    { label: "Disclaimer", href: "/disclaimer" },
  ],
};